version: '3.9'
services:
  stablediffusion-infinity:
    build: .
    ports:
    - 7575:7575
    volumes:
      - ./checkpoints/:/app/checkpoints
      - ./img/:/app/img
      - ./notebooks/:/app/notebooks
      - ./src/:/app/src
      - ./main2.ipynb:/app/main2.ipynb
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]